### PR TITLE
Meats Added and tweaks

### PR DESCRIPTION
**Pull request by Bramcraft**

### CODE REVIEW

**Comment by Yulife** [comment]
Just thought about what Hootch actually is, lol. It is low quality alcohol and I don't think meat would fit then xD Though, thanks for making it, I am an idiot T_T

**Comment by Bramcraft** [comment]
Makes sense to me! However you need to be careful how your using these pulls because there were tweaks aswell and if your not using the pulls properly, when im adding new features as well tweaks to old configs i need them to be up to date . You could just ask me to remove the meats parts before merging branchs resulting in them up to date and 100% right syntax.

**Comment by Yulife** [comment]
Don't worry, not trying to sound disrespectful but I am not merging them into the file that I use ingame, instead, I copy over the part that is needed & new so it more organized haha.

**Comment by Bramcraft** [comment]
Your the boss! But the way your doing it is not very effective and will lead to problems like you just had. Github is an huge tool and your using like pastebin, rant over! :) x

**Comment by Yulife** [comment]
Hey @Bramcraft, I just overhauled the Vat recipes.
Some points are:
-Removed Sewage Recipe (I don't think it fits, in the end)
-Removed Seeds and Saplings from Hootch
-Added a TON of fruits and veggies from different mods, list for Pam's crops is now full
-Added multipliers in form of sweeteners like honey, maple syrup and enzyme growth medium.

Full config (.xml) here http://paste.ee/p/YrKgm

**Comment by Bramcraft** [comment]
Nice work, that must of taken VERY LONG TIME. I agree with all those points, I haven't even used the sawage recipes yet and i'm mid-game. Removing the seeds and Saplings makes sense because hootch is made from rotten fruits(i think you mentioned that). I have also looked at the code and looks good, some incorrect formatting but that's no problem, haven't checked names though.

**Comment by Yulife** [comment]
Would you bring up the incorrect formatting? lol

**Comment by Bramcraft** [comment]
Its really not a problem but the ones i noticed scanning through were lines 8,20,152,153.

**Comment by Yulife** [comment]
Ehh, the pasting somehow did that. It's fine in the original config :)

**Pull request closed without merging**
