### PR TITLE
Recipes Added

### PR DESCRIPTION
**Pull request by Bramcraft**
Recipes Added were;
Ferrous Ore
Cinnibar Ore
Firestone

### CODE REVIEW

**Comment by Bramcraft** [comment]
Just checking you have seen this?

**Comment by Yulife** [comment]
How in the world did I miss this. Will check over it!

**Comment by Yulife** [comment]
For some reason the Ferrous recipe doesn't work. The strange thing is, it just displays the Platinum Dust as Ferrous Dust. I also discovered that the Ferrous recipe was in vanilla EnderIO as well, however, also just displays as Ferrous and not Platinum =/

**Comment by Bramcraft** [comment]
Guessing a unloc. name has changed i have 1.2.0 now so will test it again! And i saw that isn't that for nickel? Or its been added since 1.1.4 will look into it!

**Comment by Yulife** [comment]
Update your game with the latest EnderIO and Thermal Foundation, that should make it appear.

**Comment by Yulife** [comment]
<recipeGroup name="Thermal Expansion">
    <recipe name="FerrousOre" energyCost="3600">
      <input>
        <itemStack modID="ThermalFoundation" itemName="ItemBlockOre" itemMeta="4"/>
      </input>
      <output>
        <itemStack modID="ThermalFoundation" itemName="ItemBase" itemMeta="36" number="2"/>
        <itemStack modID="ThermalFoundation" itemName="ItemBase" itemMeta="36" number="1" chance="0.05"/>     
        <itemStack modID="ThermalFoundation" itemName="ItemBase" itemMeta="37" chance="0.1"/>      
      </output>
    </recipe>
  </recipeGroup>

**Comment by Yulife** [comment]
Could you try overriding it? Maybe that fixes it.

**Comment by Bramcraft** [comment]
Will do, are the rest still working?

**Comment by Bramcraft** [comment]
Yeah thats what i will have to do till enderio adds the change. Its doable leave it with me!

**Comment by Yulife** [comment]
No.. the rest is not working, I just discovered :/

**Comment by Bramcraft** [comment]
Are you copy and pasteing it into the config right?

**Comment by Yulife** [comment]
Yeah, I click "Raw" so it gets formatted properly, otherwise it will just fall flat.

**Comment by Yulife** [comment]
http://paste.ee/p/SR0ok
This is how my user config looks right now.

**Comment by Yulife** [comment]
Now it works!
But why... does it output 4 quicksilver? o_o
http://puu.sh/e6kBp/66207b23e1.png

**Comment by Bramcraft** [comment]
Looks right to me! Enderio must of changed something :( i will sort it!

**Comment by Yulife** [comment]
Okay, Firestone works perfectly, Cinnibar is a bit wonky xD, Ferrous still not showing Platinum.

**Comment by Bramcraft** [comment]
5 quicksilver? Because your a lucky person and thats what you asked for! Lol

**Comment by Bramcraft** [comment]
Can you send me a picture of the ferrous problem, works for me!

**Comment by Bramcraft** [comment]
Its the vanilla recipe that works but can't override it and can't find it in the core SAGmill config so not sure whats going on there tbh!

**Pull request closed without merging**
